name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master
    tags-ignore:
      - '**'

jobs:
  cheeck_formatting:
    name: 'ensure cargo fmt'
    runs-on: ubuntu-20.04
    steps:
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          default: true
          profile: minimal
          components: rustfmt
      - uses: actions/checkout@v2
      - run: cargo fmt -- --check

  build:
    name: ${{ matrix.job.target }} (${{ matrix.job.os }}) (${{ matrix.job.toolchain }})
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04, toolchain: stable }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04, toolchain: 1.66.1 }
          - { target: x86_64-unknown-linux-musl, os: ubuntu-20.04, toolchain: stable }
          # windows
          # - { target: x86_64-pc-windows-gnu, os: windows-2019 }
          # - { target: x86_64-pc-windows-gnu, os: windows-2019 }
          # osx
          - { target: x86_64-apple-darwin, os: macos-11, toolchain: stable }

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install packages (Ubuntu)
        if: matrix.job.os == 'ubuntu-20.04'
        run: |
          ci/ubuntu-install-packages

      - name: Install toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.job.toolchain }}
          target: ${{ matrix.job.target }}
          override: true
          profile: minimal

      # we need to skip this for apple silicon target
      - name: Test
        if: ${{ matrix.job.target != 'aarch64-apple-darwin' }}
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target=${{ matrix.job.target }}
